version: '3'
services:
  app:
    image: current
    ports:
      - "3000-3001:3000"
  # mongo:
  #   image: mongo:4.2.8
  #   volumes:
  #     - ./db/mongodb:/data/db
  #     - ./db/mongodb_config:/data/config
  #   ports:
  #     - "27017:27017"
##############################
# version: "3.8"

# services:
#   app:
#     image: current
#     restart: always
#     environment:
#       # MONGO_URL: "mongodb://db:27100/demo"
#       MONGO_URL: "mongodb://demo:demo@127.0.0.1:27017/demo"
#     depends_on:
#       - db
#     ports:
#       - "3000-3001:3000"

#   db:
#     image: mongo:4.2.8
#     ports: 
#       - "27017:27017"
#     environment:
#       - MONGODB_USERNAME=demo
#       - MONGODB_PASSWORD=demo
#       - MONGODB_DATABASE=demo
#     volumes:
#       - ./db/mongodb:/data/db
#       - ./db/mongodb_config:/data/config

##############################
  #command: npm run debug


# version: "3"

# services: 
#   app:
#     restart: always
#     build: .
#     ports: 
#       - "3000:3000" 
#     links: 
#       - mongo
#     expose: 
#       - "3000"
#     depends_on: 
#       - mongo
#   mongo:
#     image: mongo:4.2.8
#     restart: always
#     volumes: 
#       - ./db/mongodb:/data/db
#       - ./db/mongodb_config:/data/config
#     ports: 
#       - "27100:27017"
# networks:
#     default:
#         driver: redloopback